[environments.dev]
store = "https://aucreations-test.myshopify.com/"
ignore = ["frontend/","package.json","package-lock.json","**/*.json"]

[environments.prod]
store = "https://aucreations-test.myshopify.com/"
